export const PAYU_ORDER_VALIDITY_SECONDS = 60 * 60;
export const PAYMENT_HOLD_GRACE_SECONDS = 10 * 60;
export const PAYMENT_HOLD_MILLISECONDS = (PAYU_ORDER_VALIDITY_SECONDS + PAYMENT_HOLD_GRACE_SECONDS) * 1000;
