'use client';
import {useEffect,useState} from 'react';
import GiftCard from '@/components/GiftCard';
import {fulfillmentLabel,orderDeliveryLabel,orderLineDetails,orderMoney,paymentLabel,safeOrderImage} from '@/lib/galleries/order-presentation';

export type ClientPreviewSelection={kind:'offer'|'contract'|'gallery'|'order'|'gift-card';resourceId:number};
const money=(value:unknown)=>`${Number(value||0).toLocaleString('pl-PL')} PLN`;
const date=(value:unknown)=>value ? new Date(String(value)).toLocaleDateString('pl-PL') : '—';

export default function ClientPreviewDetail({clientId,token,selection,onBack}:{clientId:number;token:string;selection:ClientPreviewSelection;onBack:()=>void}) {
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[pdfLoading,setPdfLoading]=useState(false);
 useEffect(()=>{let active=true;const controller=new AbortController();setLoading(true);setError('');setData(null);
  fetch(`/api/admin/clients/${clientId}/preview/details/${selection.kind}/${selection.resourceId}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:controller.signal}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Nie udało się otworzyć szczegółów.');if(active)setData(body);}).catch(failure=>{if(active&&!controller.signal.aborted)setError(failure instanceof Error?failure.message:'Błąd podglądu.');}).finally(()=>{if(active)setLoading(false);});
  return()=>{active=false;controller.abort();};
 },[clientId,selection.kind,selection.resourceId,token]);
 const openPdf=async()=>{setPdfLoading(true);setError('');try{const response=await fetch(`/api/admin/clients/${clientId}/preview/details/contract/${selection.resourceId}/pdf`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'PDF jest niedostępny.');const url=URL.createObjectURL(await response.blob());window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(failure){setError(failure instanceof Error?failure.message:'PDF jest niedostępny.');}finally{setPdfLoading(false);}};
 return <main className="mx-auto max-w-6xl px-4 py-8 text-zinc-100">
  <button type="button" onClick={onBack} className="mb-6 min-h-11 rounded-xl border border-zinc-600 px-5 py-2 font-semibold hover:border-amber-300">← Wróć do panelu klienta</button>
  {loading?<p role="status" className="rounded-2xl border border-zinc-700 p-8">Ładowanie szczegółów…</p>:error&&!data?<p role="alert" className="rounded-2xl border border-red-500/40 bg-red-950 p-6">{error}</p>:data?.kind==='offer'?<OfferPreview offer={data.offer}/>:data?.kind==='contract'?<ContractPreview contract={data.contract} bank={data.bank} onPdf={openPdf} pdfLoading={pdfLoading}/>:data?.kind==='gallery'?<GalleryPreview gallery={data.gallery}/>:data?.kind==='order'?<OrderPreview order={data.order}/>:data?.kind==='gift-card'?<GiftCardPreview card={data.card}/>:null}
  {error&&data&&<p role="alert" className="mt-6 rounded-xl border border-red-500/40 bg-red-950 p-4">{error}</p>}
 </main>;
}

function OfferPreview({offer}:{offer:any}) {const template=offer.template_data||{};return <article className="space-y-8">
 <header className="rounded-3xl border border-amber-500/30 bg-gradient-to-br from-amber-500/10 to-zinc-950 p-8"><p className="text-xs font-bold uppercase tracking-widest text-amber-400">Oferta #{offer.offerNumber||offer.id} · {offer.status}</p><h1 className="mt-3 text-4xl font-bold">{offer.title}</h1>{offer.valid_until&&<p className="mt-3 text-zinc-400">Ważna do {date(offer.valid_until)}</p>}<p className="mt-5 text-3xl font-bold text-amber-300">{money(offer.total_price)}</p></header>
 {template?.eventDate||offer.session_date?<section className="rounded-2xl border border-zinc-700 p-6"><h2 className="text-xl font-bold">Termin i miejsce</h2><p className="mt-3">{date(offer.session_date||template.eventDate)} {offer.session_time||template.eventTime||''}</p><p className="text-zinc-400">{offer.session_location||template.location||''}</p></section>:null}
 {(offer.sections||[]).map((section:any)=><section key={section.id} className="rounded-2xl border border-zinc-700 bg-zinc-900/50 p-6"><h2 className="text-2xl font-bold">{section.title}</h2>{section.description&&<p className="mt-3 whitespace-pre-wrap text-zinc-300">{section.description}</p>}<div className="mt-5 divide-y divide-zinc-700">{section.items.map((item:any)=><div key={item.id} className="flex justify-between gap-4 py-4"><div><h3 className="font-semibold">{item.title}</h3>{item.description&&<p className="mt-1 whitespace-pre-wrap text-sm text-zinc-400">{item.description}</p>}</div><p className="shrink-0 font-bold text-amber-300">{money(item.price)}</p></div>)}</div></section>)}
 {offer.client_selection?.familyVoucher&&<section className="rounded-2xl border border-amber-500/30 p-6"><h2 className="text-xl font-bold">Voucher rodzinny zapisany w ofercie</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Item label="Dla" value={offer.client_selection.familyVoucher.recipientName}/><Item label="Od" value={offer.client_selection.familyVoucher.senderName}/><Item label="Pakiet" value={offer.client_selection.familyVoucher.packageName}/><Item label="Termin" value={offer.client_selection.familyVoucher.sessionDate}/></dl></section>}
 {offer.negotiations?.length>0&&<section className="rounded-2xl border border-zinc-700 p-6"><h2 className="text-xl font-bold">Ustalenia</h2>{offer.negotiations.map((entry:any)=><p key={entry.id} className="mt-3 rounded-xl bg-zinc-900 p-4"><span className="font-semibold">{entry.sender==='client'?'Klient':'Fotograf'}:</span> {entry.message}</p>)}</section>}
 </article>}

function ContractPreview({contract,bank,onPdf,pdfLoading}:{contract:any;bank:any;onPdf:()=>void;pdfLoading:boolean}) {return <article className="overflow-hidden rounded-3xl bg-white text-zinc-900 shadow-2xl"><header className="bg-slate-900 p-6 text-white"><p className="text-xs uppercase tracking-widest text-zinc-300">{contract.status}</p><h1 className="mt-2 text-3xl font-bold">Umowa {contract.contract_number||`#${contract.id}`}</h1><button type="button" onClick={onPdf} disabled={pdfLoading} className="mt-5 min-h-11 rounded-xl bg-amber-400 px-5 py-2 font-bold text-black disabled:opacity-50">{pdfLoading?'Otwieranie PDF…':'Otwórz PDF umowy'}</button></header>
 {contract.deposit_amount?<section className="border-b bg-amber-50 p-6"><h2 className="font-bold">Zaliczka: {money(contract.deposit_amount)}</h2><p>Termin: {date(contract.deposit_due_at)} · {contract.deposit_paid_at?'opłacona':'oczekuje na wpłatę'}</p>{bank?.bank_account_number&&<p className="mt-2 font-mono">{bank.bank_account_number}</p>}</section>:null}
 <section className="p-8"><div className="whitespace-pre-wrap leading-7">{contract.content||'Treść umowy nie została wpisana w systemie.'}</div></section></article>}

function GalleryPreview({gallery}:{gallery:any}) {return <article className="space-y-6"><header className="rounded-3xl border border-amber-500/30 bg-zinc-900 p-8"><p className="text-xs font-bold uppercase tracking-widest text-amber-400">{gallery.gallery_mode==='GROUP'?'Galeria grupowa':'Galeria indywidualna'} · tylko odczyt</p><h1 className="mt-2 text-4xl font-bold">{gallery.client_name}</h1>{gallery.description&&<p className="mt-4 whitespace-pre-wrap text-zinc-300">{gallery.description}</p>}<p className="mt-3 text-sm text-zinc-400">{gallery.photos.length} zdjęć · dostęp do {gallery.expires_at?date(gallery.expires_at):'bezterminowo'}</p></header>
 {gallery.gallery_mode==='GROUP'&&gallery.participants?.length>0?<section className="rounded-2xl border border-zinc-700 p-6"><h2 className="text-xl font-bold">Profile uczestników</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{gallery.participants.map((p:any)=><div key={p.id} className="rounded-xl bg-zinc-900 p-4"><p className="font-semibold">{p.avatar||'•'} {p.name}</p><p className="text-sm text-zinc-400">Wybrano {p._count.selections}/{p.max_selections} · {p.selection_status}</p></div>)}</div></section>:null}
 <section><h2 className="mb-4 text-2xl font-bold">Zdjęcia widoczne w galerii</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{gallery.photos.map((photo:any)=><figure key={photo.id} className="overflow-hidden rounded-xl border border-zinc-700 bg-zinc-900"><img src={photo.thumbnail_url||photo.file_url} alt={`Zdjęcie #${photo.id}`} className="aspect-square w-full object-cover" loading="lazy"/><figcaption className="p-2 text-xs text-zinc-400">#{photo.id}{photo.is_standard?' · pakietowe':' · dodatkowe'}</figcaption></figure>)}</div></section></article>}

function OrderPreview({order}:{order:any}) {return <article className="overflow-hidden rounded-3xl border border-zinc-700 bg-zinc-900"><header className="border-b border-zinc-700 p-6"><h1 className="text-3xl font-bold">Zamówienie #{order.id}</h1><p className="mt-2">{paymentLabel(order.paymentStatus)} · {date(order.createdAt)}</p>{order.paymentStatus==='paid'&&<p>{fulfillmentLabel(order.metadata.fulfillment.status)}</p>}</header><div className="divide-y divide-zinc-700">{order.metadata.lines.map((line:any)=><section key={line.id} className="p-6"><h2 className="text-xl font-semibold">{line.title}</h2><p className="mt-1 text-zinc-400">{orderLineDetails(line)}</p><p className="mt-2">{line.quantity} × {orderMoney(line.unitAmount)} · <b>{orderMoney(line.lineTotal)}</b></p><div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-6">{(line.kind==='print'?[line.photoId]:line.photoIds).map((id:number)=>{const photo=order.photos.find((p:any)=>p.id===id);return photo?.url?<img key={id} src={safeOrderImage(photo.url)!} alt={`Zdjęcie #${id}`} className="aspect-square w-full rounded-lg object-cover"/>:<div key={id} className="p-3">#{id}</div>})}</div></section>)}</div><footer className="space-y-2 border-t border-zinc-700 p-6"><p>{order.metadata.delivery.recipientName}</p><p>{orderDeliveryLabel(order.metadata)}</p><p className="text-2xl font-bold">Razem: {orderMoney(order.total)}</p></footer></article>}

function GiftCardPreview({card}:{card:any}) {return <article className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-widest text-amber-400">Voucher / karta podarunkowa · tylko odczyt</p><h1 className="mt-2 text-3xl font-bold">{card.card_title||'Karta podarunkowa'}</h1></header><div className="mx-auto max-w-3xl"><GiftCard code={card.code} value={Math.round(card.value)} theme={card.theme||'birthday'} cardTitle={card.card_title} cardDescription={card.card_description} recipientName={card.recipient_name} senderName={card.sender_name} message={card.message} showPrice={card.show_price!==false}/></div><dl className="grid gap-3 rounded-2xl border border-zinc-700 p-6 sm:grid-cols-2"><Item label="Status" value={card.status}/><Item label="Ważny do" value={date(card.valid_until)}/><Item label="Odbiorca" value={card.recipient_name}/><Item label="Kod" value={card.code}/></dl></article>}
function Item({label,value}:{label:string;value:unknown}) {return <div><dt className="text-xs uppercase tracking-widest text-zinc-500">{label}</dt><dd className="mt-1 font-semibold">{String(value||'—')}</dd></div>}
