const {assert,check,mount,reset,button,click}=require('./gallery-shop-dom.cjs');
const Module=require('node:module');
const {NextRequest}=require('next/server');
const {renderOrderEmail}=require('../../src/lib/galleries/order-email.ts');
const {orderOrigin}=require('../../src/lib/galleries/order-origin.ts');
const metadata={kind:'gallery_merchandise',version:1,customerId:7,lines:[{id:'album',kind:'product',title:'Harmonijka <test>',productId:2,photoIds:[4,5],coverPhotoId:4,quantity:2,unitAmount:4154,lineTotal:8308,product:{title:'Harmonijka',image_url:'https://example.com/product.jpg'}}],delivery:{method:'locker',pointCode:'PZN01M',recipientName:'Test Odbiorca',email:'recipient@example.com',phone:'500000000',amount:1700},fulfillment:{status:'new',trackingNumber:null}};
let client={id:7,email:'owner@example.com'}, rows=[], where, photoWhere, fail=false;
const db={photoOrder:{findMany:async args=>{where=args.where;return rows}},galleryPhoto:{findMany:async args=>{photoWhere=args.where;return [{id:4,thumbnail_url:'https://example.com/thumb.jpg'}]}}};
const original=Module._load;
Module._load=function(name){if(name==='@/lib/db/prisma')return {__esModule:true,default:db};if(name==='@/lib/galleries/order-account'){const real=original.apply(this,arguments);return {...real,orderClient:async()=>client};}return original.apply(this,arguments)};
const {GET}=require('../../src/app/api/account/orders/route.ts');
const AccountOrders=require('../../src/components/client/AccountOrders.tsx').default;
const req=(query='')=>new NextRequest('http://localhost/api/account/orders'+query);
const order=()=>({id:30,gallery_id:26,created_at:new Date('2026-09-15T18:10:00Z'),payment_status:'paid',total_amount:10008,product_ids:JSON.stringify(metadata)});
(async()=>{
 for(let round=1;round<=3;round++){
  metadata.delivery.email='recipient@example.com';
  await check(`round ${round}: account auth, scoped order, no checkout secrets`,async()=>{rows=[order()];client=null;assert.equal((await GET(req())).status,401);client={id:7,email:'owner@example.com'};let response=await GET(req('?order=30'));assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'private, no-store');const data=await response.json();assert.equal(data.orders[0].id,30);assert.equal(where.participant_id,null);assert.deepEqual(where.gallery.OR,[{client_id:7},{client_id:null,client_email:'owner@example.com'}]);assert.equal(photoWhere.gallery_id,26);assert.deepEqual(photoWhere.id.in,[4,5]);assert.equal(data.orders[0].paymentUrl,undefined);assert.equal(data.orders[0].idempotency_key,undefined);metadata.customerId=8;rows=[order()];assert.equal((await GET(req('?order=30'))).status,404);metadata.customerId=7;assert.equal((await GET(req('?order=-1'))).status,400);});
  await check(`round ${round}: legacy email fallback never overrides saved buyer`,async()=>{delete metadata.customerId;rows=[order()];assert.equal((await GET(req('?order=30'))).status,404);metadata.delivery.email='OWNER@example.com';rows=[order()];assert.equal((await GET(req('?order=30'))).status,200);metadata.customerId=8;rows=[order()];assert.equal((await GET(req('?order=30'))).status,404);metadata.customerId=7;});
  await check(`round ${round}: both email variants contain prices, thumbnail and proper link`,async()=>{const photos=[{id:4,url:'https://example.com/thumb.jpg'}];const customer=renderOrderEmail({id:30,total:10008,metadata,photos,url:'https://wlasniewski.pl/konto?tab=orders&order=30'});const admin=renderOrderEmail({id:30,total:10008,metadata,photos,admin:true,url:'https://wlasniewski.pl/admin/bookings/orders?order=GL-30'});assert.match(customer.html,/Harmonijka &lt;test&gt;/);assert.match(customer.html,/41,54/);assert.match(customer.html,/83,08/);assert.match(customer.html,/100,08/);assert.match(customer.html,/product.jpg/);assert.match(customer.html,/thumb.jpg/);assert.match(customer.html,/Cena za szt/);assert.match(customer.html,/tab=orders/);assert.doesNotMatch(customer.html,/Kolejność zdjęć/);assert.match(admin.html,/Kolejność zdjęć: 4, 5/);assert.match(admin.html,/admin\/bookings\/orders/);assert.match(customer.text,/PZN01M/);});
  await check(`round ${round}: client history paid, pending, network failure and retry`,async()=>{await reset();window.history.replaceState(null,'','/konto?tab=orders&order=30');let status='pending';fail=false;global.fetch=async()=>({ok:!fail,json:async()=>fail?{error:'Brak połączenia'}:{orders:[{id:30,createdAt:'2026-09-15T18:10:00Z',paymentStatus:status,total:10008,metadata,photos:[{id:4,url:'https://example.com/thumb.jpg'}]}],nextCursor:null}});await mount(AccountOrders,{token:'test'});assert.match(document.body.textContent,/Oczekujemy na potwierdzenie/);assert.doesNotMatch(document.body.textContent,/Przyjęte do realizacji/);status='paid';await click(button('Odśwież status'));assert.match(document.body.textContent,/Opłacone/);assert.match(document.body.textContent,/Przyjęte do realizacji/);fail=true;await click(button('Odśwież status'));assert.match(document.querySelector('[role="alert"]').textContent,/Brak połączenia/);fail=false;await click(button('Odśwież status'));assert.equal(document.querySelector('[role="alert"]'),null);await reset();});
 }
 await check('production return avoids Netlify alias; explicit previews retain their session domain',async()=>{const old={node:process.env.NODE_ENV,context:process.env.CONTEXT,base:process.env.NEXT_PUBLIC_BASE_URL};process.env.NODE_ENV='production';process.env.CONTEXT='production';process.env.NEXT_PUBLIC_BASE_URL='https://abc--example.netlify.app';assert.equal(orderOrigin('https://internal.netlify.app/api/shop'),'https://wlasniewski.pl');process.env.CONTEXT='deploy-preview';assert.equal(orderOrigin('https://preview.netlify.app/api/shop'),'https://preview.netlify.app');for(const [key,value] of Object.entries({NODE_ENV:old.node,CONTEXT:old.context,NEXT_PUBLIC_BASE_URL:old.base})){if(value===undefined)delete process.env[key];else process.env[key]=value;}});
})().catch(e=>{console.error(e);process.exitCode=1});
