'use client';
import {useState} from 'react';

import type {ShipmentRecord} from '@/lib/shipping/gallery-shipment';
type Configuration = {ready: boolean; missing: string[]; environment: string; pickupReady: boolean; senderSource: string};
const button = 'min-h-11 rounded-xl border border-white/20 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40';
const input = 'mt-1 min-h-11 w-full rounded-xl border border-white/15 bg-zinc-950 p-3 text-base text-white';
const statuses: Record<string,string> = {created:'Przygotowanie',offers_prepared:'Przygotowano ofertę',confirmed:'Etykieta opłacona',dispatched_by_sender:'Nadana',collected_from_sender:'Odebrana przez kuriera',taken_by_courier:'Odebrana przez kuriera',adopted_at_source_branch:'W oddziale nadawczym',sent_from_source_branch:'W drodze',out_for_delivery:'W doręczeniu',ready_to_pickup:'Gotowa do odbioru',delivered:'Doręczona',cancelled:'Anulowana',returned_to_sender:'Zwrócona nadawcy'};
export default function GalleryShipmentPanel({galleryId,orderId,method,onShipmentChange}: {galleryId:number;orderId:number;method:string;onShipmentChange?:(shipment:ShipmentRecord|null)=>void}) {
 const [open,setOpen] = useState(false),[busy,setBusy] = useState(false),[error,setError] = useState('');
 const [shipment,setShipment] = useState<ShipmentRecord|null>(null),[configuration,setConfiguration] = useState<Configuration|null>(null);
 const [template,setTemplate] = useState('small'),[weight,setWeight] = useState('1'),[length,setLength] = useState('300'),[width,setWidth] = useState('200'),[height,setHeight] = useState('100');
 const [pickupConfirmed,setPickupConfirmed] = useState(false);
 const [confirmed,setConfirmed] = useState(false),[reconcileId,setReconcileId] = useState('');
 const endpoint = `/api/admin/galleries/${galleryId}/shop/orders/${orderId}/shipment`;
 const authHeaders = () => {const token=localStorage.getItem('admin_token');return token?{Authorization:`Bearer ${token}`}:{Authorization:''};};
 const request = async (suffix = '', init?: RequestInit) => { const response = await fetch(`${endpoint}${suffix}`, {credentials:'include',...init,headers:{'Content-Type':'application/json',...authHeaders(),...init?.headers}}); const data = await response.json(); if(!response.ok) throw Error(data.error || 'Nie udało się obsłużyć przesyłki.'); if(data.configuration) setConfiguration(data.configuration); if('shipment' in data) {setShipment(data.shipment);onShipmentChange?.(data.shipment);} return data; };
 const run = async (action:()=>Promise<unknown>) => {if(busy)return;setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Błąd połączenia.');await request().catch(()=>undefined);}finally{setBusy(false);}};
 const patch = (body:unknown) => run(()=>request('',{method:'PATCH',body:JSON.stringify(body)}));
 if(!open)return <button type="button" className={button} onClick={()=>{setOpen(true);void run(()=>request());}}>Przesyłka InPost · zamówienie #{orderId}</button>;
 return <section aria-label={`Przesyłka InPost zamówienia ${orderId}`} className="space-y-4 rounded-2xl border border-amber-200/20 bg-zinc-950/40 p-4">
  <div className="flex flex-wrap justify-between gap-3"><h5 className="font-semibold text-white">Przesyłka InPost · {method==='locker'?'Paczkomat':'Kurier'}</h5><span className="text-xs text-amber-200">{configuration ? (configuration.environment==='production'?'Środowisko produkcyjne':'Środowisko testowe') : 'Sprawdzanie środowiska…'}</span></div>
  {error&&<p role="alert" className="text-sm text-red-200">{error}</p>}
  {!configuration && <button type="button" disabled={busy} className={button} onClick={()=>run(()=>request())}>{busy?'Wczytywanie…':'Wczytaj konfigurację'}</button>}
  {configuration&&!configuration.ready&&<div className="space-y-2 text-sm text-amber-100"><p>Integracja wymaga konfiguracji serwera:</p><ul className="list-inside list-disc">{configuration.missing.map(item=><li key={item}>{item}</li>)}</ul><p>Token i identyfikator organizacji pochodzą z konta ShipX dla wybranego środowiska. Nie wpisuj tokena w danych produktu ani klienta.</p></div>}
  {configuration?.ready&&!shipment&&<><p className="text-sm text-zinc-300">Dane odbiorcy pochodzą z opłaconego zamówienia. {configuration.senderSource==='organization'?'Nadawca jest pobierany z konta InPost.':'Nadawca pochodzi z konfiguracji serwera.'}</p><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2">{method==='locker'?<label className="text-sm">Gabaryt paczki<select className={input} value={template} onChange={e=>setTemplate(e.target.value)}><option value="small">A · 8 × 38 × 64 cm</option><option value="medium">B · 19 × 38 × 64 cm</option><option value="large">C · 41 × 38 × 64 cm</option></select></label>:<>{[['Długość (mm)',length,setLength],['Szerokość (mm)',width,setWidth],['Wysokość (mm)',height,setHeight]].map(([label,value,setter])=><label key={String(label)} className="text-sm">{String(label)}<input className={input} type="number" min="1" max="1200" value={String(value)} onChange={e=>(setter as (value:string)=>void)(e.target.value)}/></label>)}</>}<label className="text-sm">Waga (kg)<input className={input} type="number" min="0.01" max="25" step="0.01" value={weight} onChange={e=>setWeight(e.target.value)}/></label></fieldset><label className="flex items-start gap-3 text-sm leading-relaxed"><input type="checkbox" className="mt-1" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Potwierdzam zakup usługi nadania według umowy i cennika mojego konta InPost. Odbiór przez kuriera zamawiam oddzielnie.</label><button type="button" disabled={busy||!confirmed} className={`${button} bg-amber-200/10`} onClick={()=>run(()=>request('',{method:'POST',body:JSON.stringify({confirmCharge:true,parcel:{template,length:Number(length),width:Number(width),height:Number(height),weight:Number(weight)}})}))}>{busy?'Przetwarzanie…':'Utwórz i opłać przesyłkę'}</button></>}
  {shipment&&<div className="space-y-3"><p className="text-sm text-zinc-300">Numer referencyjny: <strong className="break-all">{shipment.reference}</strong></p><p className="font-semibold text-white">{shipment.state==='uncertain'||shipment.state==='creating'?'Nadanie wymaga potwierdzenia':statuses[shipment.status||'']||shipment.status||shipment.state}</p>{shipment.trackingNumber&&<p className="break-all text-sm text-amber-100">Numer przesyłki: {shipment.trackingNumber}</p>}{shipment.shipmentId&&<div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy} onClick={()=>run(()=>request('?refresh=1'))}>Odśwież status InPost</button>{shipment.state==='created'&&<button type="button" className={button} disabled={busy} onClick={()=>run(async()=>{const response=await fetch(`${endpoint}/label`,{credentials:'include',headers:authHeaders()});if(!response.ok){const data=await response.json();throw Error(data.error||'Etykieta nie jest jeszcze gotowa.');}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`inpost-${orderId}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);})}>Pobierz etykietę PDF</button>}{shipment.state==='created'&&['created','offers_prepared'].includes(shipment.status||'')&&<button type="button" className={button} disabled={busy} onClick={()=>patch({action:'cancel'})}>Anuluj nieopłaconą przesyłkę</button>}</div>}
  {!shipment.shipmentId&&<div className="space-y-3 text-sm text-amber-100"><p>Ponowne nadanie jest zablokowane. Sprawdź ShipX według numeru referencyjnego. Jeżeli przesyłka powstała, wpisz jej ID z API — system sprawdzi zgodność z zamówieniem.</p><label className="block">ID istniejącej przesyłki<input className={input} type="number" min="1" value={reconcileId} onChange={e=>setReconcileId(e.target.value)}/></label><button type="button" className={button} disabled={busy||!reconcileId} onClick={()=>patch({action:'reconcile',shipmentId:Number(reconcileId)})}>Sprawdź i połącz przesyłkę</button></div>}
  {shipment.state==='created'&&shipment.status==='confirmed'&&!shipment.dispatch&&<div className="space-y-3 border-t border-white/10 pt-3"><p className="text-sm text-zinc-300">Odbiór paczki przez kuriera jest osobnym zleceniem rozliczanym według konta InPost.</p>{configuration?.pickupReady?<><label className="flex gap-3 text-sm"><input type="checkbox" checked={pickupConfirmed} onChange={e=>setPickupConfirmed(e.target.checked)}/>Potwierdzam zamówienie odbioru pod adresem nadawcy.</label><button type="button" disabled={busy||!pickupConfirmed} className={button} onClick={()=>patch({action:'pickup',confirmCharge:true})}>Zamów odbiór kuriera</button></>:<p className="text-sm text-amber-100">Do odbioru kuriera potrzebny jest INPOST_SENDER_JSON z nazwą, telefonem, e-mailem i adresem nadawcy.</p>}</div>}
  {shipment.dispatch&&<p className="text-sm text-zinc-300">Odbiór kuriera: {shipment.dispatch.state==='created'?`zlecony · ${shipment.dispatch.id}`:'wymaga sprawdzenia w ShipX; ponowienie zablokowane'}</p>}
  </div>}
 </section>;
}
