'use client';

import { lazy, Suspense, useCallback, useEffect, useState } from 'react';
const MediaPicker = lazy(() => import('@/components/admin/MediaPicker'));
import NphotoStarterCatalog from './NphotoStarterCatalog';
import NphotoOfferImporter from './NphotoOfferImporter';
import PublicShopOfferSettings from './PublicShopOfferSettings';
import ShopIntegrationCheck from './ShopIntegrationCheck';
import {visibleOfferCount} from '@/lib/galleries/shop-publication';
import Link from 'next/link';
import { GalleryProductPreviewDialog } from '@/components/galleries/GalleryProductPreview';


import { validateShopConfig, type PrintFormat, type ShopConfig, type ProductShopRule } from '@/lib/galleries/merchandise';
type Product = { id: number; title: string; description?: string | null; image_url?: string | null; preview_images?: string[]; video_url?: string | null; sample_pages?: string[]; price: number; is_active: boolean };
type Photo = { id: number; file_url: string; thumbnail_url?: string | null };
type Album = { id: number; title: string; format?: string | null; cover_image_url?: string | null };
const inputClass = 'mt-2 w-full min-w-0 min-h-12 rounded-xl border border-white/15 bg-zinc-950/60 px-3.5 py-3 text-base text-white shadow-inner transition focus:border-amber-200/60 focus:outline-none focus:ring-2 focus:ring-amber-200/30';
const buttonClass = 'min-h-11 rounded-xl border border-white/20 bg-white/[0.04] px-4 py-2.5 text-sm font-semibold text-zinc-100 transition hover:border-amber-200/40 hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-200 disabled:cursor-not-allowed disabled:opacity-40';
const panelClass = 'min-w-0 space-y-4 rounded-2xl border border-white/10 bg-zinc-900/80 p-4 sm:p-6';
const money = (amount: number) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(amount / 100);
const amountFromInput = (value: string) => value === '' ? NaN : Math.round(Number(value.replace(',', '.')) * 100);
const moneyValue = (value: number) => Number.isFinite(value) ? value / 100 : '';
const validAmount = (value: number) => Number.isSafeInteger(value) && value >= 0 && value <= 100000000;

export default function GalleryShopAdmin({ galleryId, photos = [] }: { galleryId: number | 'default'; photos?: Photo[] }) {
    const [config, setConfig] = useState<ShopConfig | null>(null);
    const [products, setProducts] = useState<Product[]>([]);
    const [sharedProducts, setSharedProducts] = useState<Product[]>([]);
    const [inherited, setInherited] = useState(false);
    const [previewMode,setPreviewMode]=useState<'shared'|'isolated'|null>(null);
    const isDefault = galleryId === 'default';
    const [albums, setAlbums] = useState<Album[]>([]);
    const [loading, setLoading] = useState(true);
    const [busy, setBusy] = useState(false);
    const [error, setError] = useState('');
    const [notice, setNotice] = useState('');
    const [albumId, setAlbumId] = useState('');
    const [albumPrice, setAlbumPrice] = useState('');
    const [dirty, setDirty] = useState(false);
    const [importDirty, setImportDirty] = useState(false);
    const [productDrafts, setProductDrafts] = useState<Record<number, boolean>>({});
    const hasProductDrafts = Object.values(productDrafts).some(Boolean);
    const base = `admin/galleries/${galleryId}/shop`;
    const request = useCallback(async (path: string, init?: RequestInit) => {
        const token = localStorage.getItem('admin_token');
        const response = await fetch(`/api/${path}`,  { credentials: 'include', ...init, headers: { 'Content-Type': 'application/json', ...(token ? {Authorization:`Bearer ${token}`} : {}), ...init?.headers } });
        const data = await response.json();
        if (!response.ok || data.success === false) throw new Error(data.error || 'Nie udało się zapisać zmian. Spróbuj ponownie.');
        return data;
    }, []);
    const load = useCallback(async (signal?: AbortSignal) => {
        const data = await request(base, { signal });
        if (signal?.aborted) return;
        const preview = data.preview || /^deploy-preview-\d+--.*\.netlify\.app$/.test(window.location.hostname);
        setPreviewMode(preview ? data.isolatedReview ? 'isolated' : 'shared' : null);
        setConfig(data.config); setInherited(data.inherited === true); setSharedProducts(data.sharedProducts || []); setProducts(data.products || []); setAlbums(data.nphotoAlbums || []); setDirty(false); setProductDrafts({}); setImportDirty(false);
    }, [base, request]);
    useEffect(() => { const controller = new AbortController(); setLoading(true); setConfig(null); setError(''); setNotice(''); load(controller.signal).catch(e => { if (!controller.signal.aborted) setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [load]);
    useEffect(() => {
        const handler = (event: BeforeUnloadEvent) => { if (dirty || hasProductDrafts || importDirty) { event.preventDefault(); event.returnValue = ''; } };
        window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler);
    }, [dirty, hasProductDrafts, importDirty]);
    const update = (patch: Partial<ShopConfig>) => { setConfig(current => current ? { ...current, ...patch } : null); setDirty(true); setNotice(''); };
    const run = async (action: () => Promise<void>, message: string) => {
        if (busy) return; setBusy(true); setError(''); setNotice('');
        try { await action(); setNotice(message); } catch (e) { setError(e instanceof Error ? e.message : 'Błąd połączenia'); } finally { setBusy(false); }
    };
    const save = () => run(async () => {
        if (!config) return;
        if (!config.title.trim() || !config.buttonLabel.trim()) throw new Error('Uzupełnij nagłówek i tekst przycisku.');
        if (config.formats.some(f => !f.label.trim() || !f.paper.trim() || !validAmount(f.unitAmount) || (f.active && f.unitAmount === 0) || !Number.isInteger(f.widthMm) || f.widthMm < 1 || !Number.isInteger(f.heightMm) || f.heightMm < 1)) throw new Error('Każdy format wymaga nazwy, dodatniej ceny i wymiarów w pełnych milimetrach.');
        if (Object.values(config.productRules).some(r => !Number.isInteger(r.minPhotos) || !Number.isInteger(r.maxPhotos) || r.minPhotos < 1 || r.maxPhotos < r.minPhotos)) throw new Error('Sprawdź minimalną i maksymalną liczbę zdjęć w produktach.');
        if (Object.values(config.delivery).some(d => !validAmount(d.amount))) throw new Error('Podaj poprawne ceny dostawy.');
        const checkedConfig = validateShopConfig(config);
        await request(base, { method: 'PUT', body: JSON.stringify({ config: checkedConfig }) });
        const data = await request(base); setConfig(data.config); setInherited(data.inherited === true); setDirty(false);
    }, 'Zapisano i ponownie odczytano ustawienia sklepu.');
    if (loading) return <section className="rounded-2xl border border-zinc-800 p-6" aria-busy="true">Wczytywanie sklepu galerii…</section>;
    if (!config) return <section className="rounded-2xl border border-red-800 p-6"><p role="alert">{error || 'Nie udało się wczytać ustawień.'}</p><button type="button" className={buttonClass} onClick={() => run(load, 'Wczytano ustawienia.')}>Spróbuj ponownie</button></section>;
    const activeFormats = config.formats.filter(format => format.active && format.unitAmount > 0).length;
    const activeProducts = [...sharedProducts, ...products].filter(product => product.is_active && product.price > 0).length;
    const publicCount=visibleOfferCount(config,products);
    const hasDelivery = config.delivery.locker.enabled || config.delivery.courier.enabled;
    const hasOffer = activeFormats + activeProducts > 0;
    const selectedAlbum = albums.find(album => String(album.id) === albumId);
    const steps = [
        { label: 'Oferta', done: hasOffer, detail: `${activeFormats} formatów · ${activeProducts} produktów`, target: activeFormats ? 'prints' : 'products' },
        { label: 'Dostawa', done: hasDelivery, detail: hasDelivery ? 'Metoda dostawy wybrana' : 'Wybierz sposób dostawy', target: 'delivery' },
        { label: 'Publikacja', done: (isDefault?publicCount>0:config.enabled) && !dirty, detail: dirty ? 'Zapisz zmiany' : isDefault ? publicCount>0 ? `${publicCount} pozycji w sklepie` : 'Brak widocznej oferty publicznej' : config.enabled ? 'Sklep włączony' : 'Sklep wyłączony', target: 'visibility' },
    ];
    const editFormat = (index: number, patch: Partial<PrintFormat>) => update({ formats: config.formats.map((f, i) => i === index ? { ...f, ...patch } : f) });
    return <section aria-label="Sklep prywatnej galerii" className="w-full min-w-0 space-y-6 rounded-3xl border border-white/10 bg-[#141416] p-4 text-zinc-200 shadow-xl sm:p-7">
        <header className="flex flex-wrap items-start justify-between gap-5">
            <div className="max-w-xl"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-amber-200/80">{isDefault ? 'Standard sprzedaży' : 'Sprzedaż w galerii'}</p><h3 className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">{isDefault ? 'Wspólna oferta galerii' : 'Sklep prywatnej galerii'}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-400">{isDefault ? 'Ustal formaty, ceny, produkty nPhoto i dostawę raz. Galerie bez własnych ustawień korzystają z tej oferty automatycznie.' : 'Przygotuj ofertę odbitek i produktów nPhoto. Klient wybierze zdjęcia, produkty i dostawę w jednym koszyku.'}</p></div>
            <span className={`rounded-full border px-3 py-2 text-xs font-semibold ${config.enabled && hasOffer && hasDelivery && (!isDefault || publicCount > 0) && !dirty ? 'border-emerald-400/30 bg-emerald-400/10 text-emerald-200' : 'border-amber-200/25 bg-amber-200/10 text-amber-200'}`}>{dirty ? 'Niezapisane zmiany' : config.enabled && hasOffer && hasDelivery && (!isDefault || publicCount > 0) ? 'Oferta aktywna' : config.enabled ? (isDefault && !publicCount ? 'Oferta publiczna jest pusta' : 'Uzupełnij ofertę') : 'Przygotowanie oferty'}</span>
        </header>
        {previewMode && <p role="note" className="rounded-xl border border-amber-200/30 bg-amber-200/10 p-4 text-sm leading-relaxed text-amber-100">{previewMode==='shared' ? 'To podgląd strony korzystający ze wspólnej bazy. Zapis oferty może zmienić również sklep produkcyjny. Testy płatności wykonuj dopiero na odizolowanej bazie.' : 'To odizolowane środowisko testowe. Zapisy nie zmieniają oferty produkcyjnej; wiadomości i produkcyjne nadania są wyłączone.'}</p>}
        <div className="grid gap-3 sm:grid-cols-3">{steps.map((step, index) => <a key={step.label} href={`#shop-${galleryId}-${step.target}`} className="group flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.025] p-4 transition hover:bg-white/[0.06]"><span aria-hidden="true" className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-sm ${step.done ? 'bg-emerald-300/10 text-emerald-200' : 'bg-white/5 text-zinc-400'}`}>{step.done ? '✓' : `0${index + 1}`}</span><span><span className="block text-sm font-semibold text-white">{step.label}</span><span className="mt-0.5 block text-xs leading-relaxed text-zinc-400">{step.detail}</span></span></a>)}</div>
        <div className="flex flex-wrap gap-2 border-b border-white/10 pb-5" aria-label="Obsługa sklepu"><Link href={isDefault ? '/admin/bookings/orders' : `/admin/bookings/orders?gallery=${galleryId}`} className={buttonClass}>{isDefault ? 'Rezerwacje → Zamówienia' : 'Zamówienia tej galerii'}</Link><a href={isDefault ? "#nphoto-launch" : "/admin/gallery-shop"} className={`${buttonClass} sm:ml-auto`}>Wspólna kolekcja nPhoto</a></div>
        {!isDefault && <div className={`rounded-2xl border p-4 sm:p-5 ${inherited ? 'border-emerald-300/20 bg-emerald-300/5' : 'border-amber-200/20 bg-amber-200/5'}`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-xl"><h4 className="font-semibold text-white">{inherited ? 'Wspólna oferta — bez dodatkowej konfiguracji' : 'Indywidualne ustawienia tej galerii'}</h4><p className="mt-2 text-sm leading-relaxed text-zinc-300">{inherited ? 'Formaty, ceny i dostawa pochodzą ze wspólnej oferty. Nie musisz ustawiać ich każdemu klientowi. Zapis poniższych ustawień utworzy wyjątek tylko dla tej galerii.' : 'Ta galeria ma własny cennik lub dostawę. Możesz wrócić do wspólnego standardu bez zmieniania wcześniejszych zamówień.'}</p></div><a href="/admin/gallery-shop" className={buttonClass}>Edytuj wspólną ofertę</a></div>{!inherited && <button type="button" className={`${buttonClass} mt-4`} disabled={busy || dirty || hasProductDrafts} onClick={() => run(async () => { await request(base, { method: 'DELETE' }); await load(); }, 'Przywrócono wspólną ofertę galerii.')}>Przywróć wspólną ofertę</button>}</div>}
        {error && <p role="alert" className="rounded-lg bg-red-950 p-3 text-red-100">{error}</p>}
        {notice && <p role="status" className="rounded-lg bg-emerald-950 p-3 text-emerald-100">{notice}</p>}
        {hasProductDrafts && <p className="rounded-xl border border-amber-200/20 bg-amber-200/5 p-3 text-sm text-amber-200">Masz niezapisane zmiany produktów. Zapisz je przy każdej edytowanej karcie produktu.</p>}
        {dirty && <p className="text-sm text-amber-300">Masz niezapisane ustawienia oferty. Zapisz je przed opuszczeniem strony.</p>}
        <div className="space-y-6">
            {isDefault && <NphotoOfferImporter disabled={busy || dirty || hasProductDrafts} onImported={load} onDirtyChange={setImportDirty} onBusyChange={setBusy} />}
            {isDefault && !dirty && !hasProductDrafts && !importDirty && <details id="nphoto-launch" open className="rounded-2xl border border-white/10 p-4"><summary className="min-h-11 cursor-pointer text-sm font-semibold text-zinc-300">Gotowe propozycje startowe nPhoto</summary><NphotoStarterCatalog onImported={load} onBusyChange={setBusy} disabled={busy} /></details>}
            {isDefault && <PublicShopOfferSettings value={config.publicOffer} formats={config.formats} products={products} shopEnabled={config.enabled} delivery={config.delivery} productRules={config.productRules} disabled={busy} onChange={publicOffer => update({ publicOffer })} onPublish={hasProductDrafts || importDirty ? undefined : () => run(async () => { const checked = validateShopConfig(config); await request(base,{method: 'PUT',body:JSON.stringify({config:checked,publishSelected:true})}); await load(); }, 'Opublikowano wycenione produkty i ponownie odczytano ofertę. Otwórz zapisany sklep.')} />}
            <fieldset id={`shop-${galleryId}-visibility`} disabled={busy} className={panelClass}><legend className="px-2 text-lg font-semibold text-white">Widoczność i treści</legend>
                <label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={config.enabled} onChange={e => update({ enabled: e.target.checked })} />Sklep aktywny</label><p className="text-sm leading-relaxed text-zinc-400">{isDefault ? 'Włącz po przygotowaniu cen i dostawy, a następnie zapisz. Oferta trafi do galerii korzystających ze wspólnego standardu.' : 'Włącz po przygotowaniu cen i dostawy, a następnie zapisz ustawienia. Zapis tworzy ustawienia indywidualne tej galerii.'}</p>
                <div className="grid gap-4 lg:grid-cols-2"><label className="text-sm">Nagłówek sklepu<input className={inputClass} value={config.title} maxLength={160} onChange={e => update({ title: e.target.value })} /></label><label className="text-sm">Tekst przycisku<input className={inputClass} value={config.buttonLabel} maxLength={80} onChange={e => update({ buttonLabel: e.target.value })} /></label></div>
                <label className="block text-sm">Opis sklepu<textarea className={inputClass} value={config.introduction} maxLength={2000} rows={3} onChange={e => update({ introduction: e.target.value })} /></label>
            </fieldset>
            <fieldset id={`shop-${galleryId}-prints`} disabled={busy} className={panelClass}><legend className="px-2 text-lg font-semibold text-white">Formaty odbitek i ceny za sztukę</legend>
                <p className="text-sm text-zinc-400">Klient może nadać ten sam format i liczbę sztuk wielu zaznaczonym zdjęciom. Zmiana cennika nie zmienia wcześniej złożonych zamówień.</p>
                {config.formats.length === 0 && <div className="rounded-xl border border-dashed border-white/15 p-5 text-sm leading-relaxed text-zinc-400">Dodaj pierwszy format, jego cenę i rodzaj papieru. Możesz również prowadzić sprzedaż samych produktów nPhoto.</div>}
                {config.formats.map((format, index) => <div key={format.id} className="grid items-end gap-4 rounded-xl border border-white/10 bg-zinc-950/40 p-4 sm:grid-cols-2 xl:grid-cols-3">
                    <label className="text-sm">Format {index + 1} nazwa<input className={inputClass} value={format.label} onChange={e => editFormat(index, { label: e.target.value })} /></label>
                    <label className="text-sm">Format {index + 1} szerokość (mm)<input className={inputClass} type="number" min="1" step="1" value={Number.isFinite(format.widthMm) ? format.widthMm : ''} onChange={e => editFormat(index, { widthMm: e.target.value === '' ? NaN : Number(e.target.value) })} /></label>
                    <label className="text-sm">Format {index + 1} wysokość (mm)<input className={inputClass} type="number" min="1" step="1" value={Number.isFinite(format.heightMm) ? format.heightMm : ''} onChange={e => editFormat(index, { heightMm: e.target.value === '' ? NaN : Number(e.target.value) })} /></label>
                    <label className="text-sm">Format {index + 1} cena (zł)<input className={inputClass} type="number" min="0.01" step="0.01" value={moneyValue(format.unitAmount)} onChange={e => editFormat(index, { unitAmount: amountFromInput(e.target.value) })} /></label>
                    <label className="text-sm">Format {index + 1} papier<input className={inputClass} value={format.paper} onChange={e => editFormat(index, { paper: e.target.value })} /></label>
                    <label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={format.active} onChange={e => editFormat(index, { active: e.target.checked })} />Format {index + 1} aktywny</label>
                    <button type="button" className={buttonClass} onClick={() => update({ formats: config.formats.filter((_, i) => i !== index), ...(config.publicOffer ? { publicOffer: { ...config.publicOffer, formatIds: config.publicOffer.formatIds.filter(id => id !== format.id) } } : {}) })}>Usuń format {index + 1}</button>
                    <div className="space-y-3 sm:col-span-2 xl:col-span-3"><p className="text-sm text-zinc-400">Cena ilościowa obejmuje wszystkie odbitki tego formatu w koszyku, również z różnych zdjęć.</p>{(format.priceTiers || []).map((tier, tierIndex) => <div key={tierIndex} className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Format {index + 1} próg {tierIndex + 1} od sztuk<input className={inputClass} type="number" min="2" step="1" value={tier.minQuantity || ''} onChange={e => editFormat(index,{priceTiers:format.priceTiers!.map((value,i)=>i===tierIndex?{...value,minQuantity:Number(e.target.value)}:value)})} /></label><label className="text-sm">Format {index + 1} próg {tierIndex + 1} cena za sztukę (zł)<input className={inputClass} type="number" min="0.01" step="0.01" value={moneyValue(tier.unitAmount)} onChange={e => editFormat(index,{priceTiers:format.priceTiers!.map((value,i)=>i===tierIndex?{...value,unitAmount:amountFromInput(e.target.value)}:value)})} /></label><button type="button" className={`${buttonClass} self-end`} onClick={()=>editFormat(index,{priceTiers:format.priceTiers!.filter((_,i)=>i!==tierIndex)})}>Usuń próg {tierIndex + 1}</button></div>)}<button type="button" className={buttonClass} disabled={(format.priceTiers?.length || 0)>=10} onClick={()=>editFormat(index,{priceTiers:[...(format.priceTiers || []),{minQuantity:(format.priceTiers?.at(-1)?.minQuantity || 1)+1,unitAmount:format.priceTiers?.at(-1)?.unitAmount || format.unitAmount}]})}>Dodaj próg cenowy — format {index + 1}</button></div>
                </div>)}
                <button type="button" className={buttonClass} onClick={() => update({ formats: [...config.formats, { id: `format-${Date.now()}`, label: '', widthMm: 100, heightMm: 150, unitAmount: 0, active: false, paper: 'mat' }] })}>Dodaj format</button>
            </fieldset>
            <fieldset id={`shop-${galleryId}-delivery`} disabled={busy} className={panelClass}><legend className="px-2 text-lg font-semibold text-white">Dostawa od Foto-Dron do klienta</legend>
                {isDefault && <ShopIntegrationCheck />}
                <p className="text-sm text-amber-200">Ustal cenę dostawy, którą klient zobaczy w podsumowaniu. Dane do wysyłki zapiszą się przy zamówieniu. Po skonfigurowaniu integracji InPost możesz w panelu „Rezerwacje → Zamówienia” utworzyć przesyłkę, pobrać etykietę i sprawdzić jej status.</p>
                <div className="grid gap-4 sm:grid-cols-2">{(['locker', 'courier'] as const).map(key => { const label = key === 'locker' ? 'Paczkomat' : 'Kurier'; return <div key={key} className="rounded-xl border border-zinc-700 p-4"><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={config.delivery[key].enabled} onChange={e => update({ delivery: { ...config.delivery, [key]: { ...config.delivery[key], enabled: e.target.checked } } })} />{label} dostępny</label><label className="text-sm">Cena dostawy {label} (zł)<input className={inputClass} type="number" min="0" step="0.01" value={moneyValue(config.delivery[key].amount)} onChange={e => update({ delivery: { ...config.delivery, [key]: { ...config.delivery[key], amount: amountFromInput(e.target.value) } } })} /></label></div>; })}</div>
            </fieldset>

            <div id={`shop-${galleryId}-products`} className={panelClass}><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="text-lg font-semibold text-white">{isDefault ? 'Produkty nPhoto we wspólnej ofercie' : 'Produkty nPhoto w tej galerii'}</h4><p className="mt-2 max-w-2xl text-sm leading-relaxed text-zinc-400">Wybierz produkt, ustal własną cenę i pokaż go klientowi ze zdjęciem oraz opisem. Zamówienie realizujesz w nPhoto, odbierasz w Foto-Dron i wysyłasz klientowi.</p></div><span className="rounded-full bg-white/5 px-3 py-1.5 text-xs text-zinc-400">{activeProducts} widocznych</span></div><p className="text-xs leading-relaxed text-zinc-500">We wspólnej ofercie możesz zaimportować przygotowane propozycje nPhoto ze zdjęciami i parametrami lub dodać produkt z własnego katalogu. Import nie składa zamówienia u producenta — zamówienie w nPhoto realizujesz osobno.</p>
                <details className="rounded-xl border border-white/10 p-4"><summary className="min-h-11 cursor-pointer text-sm text-zinc-400">Dodaj z wcześniejszego katalogu — opcjonalnie</summary><div className="mt-3 space-y-4">
                <div className="grid items-end gap-3 lg:grid-cols-3"><label className="text-sm">Produkt z katalogu<select className={inputClass} value={albumId} onChange={e => setAlbumId(e.target.value)}><option value="">Wybierz produkt</option>{albums.map(a => <option key={a.id} value={a.id}>{a.title}{a.format ? ` · ${a.format}` : ''}</option>)}</select></label><label className="text-sm">Twoja cena produktu (zł)<input className={inputClass} type="number" min="0.01" step="0.01" value={albumPrice} onChange={e => setAlbumPrice(e.target.value)} /></label><button type="button" className={buttonClass} disabled={busy || !albumId || dirty || hasProductDrafts} onClick={() => run(async () => { const price = amountFromInput(albumPrice); if (!validAmount(price) || price === 0) throw new Error('Podaj dodatnią cenę produktu.'); await request(`${base}/products`, { method: 'POST', body: JSON.stringify({ nphotoAlbumId: Number(albumId), price }) }); await load(); setAlbumId(''); setAlbumPrice(''); }, isDefault ? 'Dodano produkt do wspólnej oferty.' : 'Dodano produkt do prywatnej galerii.')}>{isDefault ? 'Dodaj produkt do wspólnej oferty' : 'Dodaj produkt do galerii'}</button></div>
                {selectedAlbum && <div className="flex items-center gap-4 rounded-xl border border-amber-200/20 bg-amber-200/5 p-4">{selectedAlbum.cover_image_url && <img src={selectedAlbum.cover_image_url} alt={selectedAlbum.title} className="h-20 w-20 rounded-lg bg-white/5 object-contain" loading="lazy" />}<div><p className="font-semibold text-white">{selectedAlbum.title}</p><p className="mt-1 text-sm text-zinc-400">{selectedAlbum.format || 'Produkt z Twojego katalogu'} · {isDefault ? 'opis i zdjęcie zostaną skopiowane do wspólnej oferty.' : 'opis i zdjęcie zostaną skopiowane do tej galerii.'}</p></div></div>}
                {!albums.length && <div className="rounded-xl border border-dashed border-white/15 p-5"><p className="font-medium text-white">Najpierw przygotuj katalog nPhoto</p><p className="mt-2 text-sm leading-relaxed text-zinc-400">Dodaj album, fotoksiążkę lub inny produkt ze zdjęciem i opisem. Oznacz go jako aktywny, aby był dostępny do przypisania.</p><a href="/admin/nphoto-albums" target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex min-h-11 items-center font-semibold text-amber-200 underline underline-offset-4">Dodaj produkty w katalogu ↗</a><button type="button" className={`${buttonClass} ml-3`} disabled={busy || dirty} onClick={() => run(async () => { const data = await request(base); setAlbums(data.nphotoAlbums || []); }, 'Odświeżono katalog nPhoto.')}>Odśwież katalog</button></div>}
                </div></details>
                {dirty && <p className="text-sm text-amber-300">Zapisz ustawienia przed dodaniem produktu.</p>}
                {!products.length && !sharedProducts.length && <p className="text-sm text-zinc-300">{isDefault ? 'Wspólna oferta nie ma jeszcze produktów.' : 'Nie przypisano produktów do tej galerii.'} Dodaj pierwszy produkt powyżej — potem dopracujesz jego prezentację i liczbę zdjęć.</p>}
                {!isDefault && sharedProducts.length > 0 && <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><h5 className="font-semibold text-white">Produkty ze wspólnej oferty</h5><a href="/admin/gallery-shop" className="text-sm font-semibold text-amber-200 underline underline-offset-4">Zarządzaj wspólnymi produktami</a></div><div className="grid gap-3 sm:grid-cols-2">{sharedProducts.map(product => <div key={product.id} className="flex min-w-0 items-center gap-3 rounded-xl border border-white/10 bg-white/[0.025] p-3">{product.image_url && <img src={product.image_url} alt={product.title} loading="lazy" className="h-20 w-20 shrink-0 rounded-lg bg-[#efede8] object-contain" />}<div className="min-w-0"><p className="break-words font-medium text-white">{product.title}</p><p className="mt-1 text-sm text-amber-200">{money(product.price)}</p><p className="mt-1 text-xs text-zinc-400">{product.is_active ? 'Ze wspólnego katalogu' : 'Ukryty'}</p></div></div>)}</div><p className="text-xs leading-relaxed text-zinc-400">Te produkty są dostępne bez przypisywania każdemu klientowi. Poniżej możesz dodać produkty tylko dla tej galerii.</p></div>}
                <div className="grid items-start gap-4 xl:grid-cols-2">{products.map(product => <ProductEditor key={product.id} product={product} disabled={busy} onDirty={value => setProductDrafts(current => ({ ...current, [product.id]: value }))} rule={config.productRules[String(product.id)] || { minPhotos: 1, maxPhotos: 50 }} onRule={rule => update({ productRules: { ...config.productRules, [product.id]: rule } })} onSave={patch => run(async () => { const data = await request(`${base}/products/${product.id}`, { method: 'PATCH', body: JSON.stringify(patch) }); setProducts(current => current.map(p => p.id === product.id ? (data.product || { ...p, ...patch }) : p)); setProductDrafts(current => ({ ...current, [product.id]: false })); }, 'Zapisano produkt.')} />)}</div>
            </div>
            <div className="sticky bottom-2 z-10 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-amber-200/20 bg-zinc-950/95 p-4 shadow-2xl backdrop-blur"><button type="button" disabled={busy || !dirty} onClick={save} className="min-h-12 rounded-xl bg-[#ead5ad] px-6 py-3 font-semibold text-zinc-950 transition hover:bg-[#f4e4c7] disabled:opacity-40">{busy ? 'Zapisywanie…' : 'Zapisz ustawienia sklepu'}</button><span className="text-sm text-zinc-400">{isDefault ? 'Ceny w PLN. Zapis aktualizuje wspólny standard galerii.' : 'Ceny w PLN. Zapis tworzy wyjątek dla tej galerii.'}</span></div>
        </div>
    </section>;
}

function ProductEditor({ product, rule, disabled, onRule, onSave, onDirty }: { onDirty: (dirty: boolean) => void; product: Product; rule: ProductShopRule; disabled: boolean; onRule: (value: ProductShopRule) => void; onSave: (patch: Product) => void }) {
    const [draft, setDraft] = useState(product);
    const [mediaOpen, setMediaOpen] = useState(false);
    const [previewOpen, setPreviewOpen] = useState(false);
    const editDraft = (next: Product) => { setDraft(next); onDirty(JSON.stringify(next) !== JSON.stringify(product)); };
    const [validation, setValidation] = useState('');
    useEffect(() => { setDraft(product); }, [product]);
    return <fieldset disabled={disabled} className="min-w-0 space-y-4 rounded-2xl border border-white/10 bg-zinc-950/40 p-4 sm:p-5"><legend className="px-2 text-sm font-semibold">Produkt #{product.id} — {product.title}</legend>
        <div className="overflow-hidden rounded-xl border border-white/10 bg-zinc-900"><div className="flex aspect-[4/3] items-center justify-center bg-[#efede8] p-5">{draft.image_url && /^https?:\/\//i.test(draft.image_url) ? <img src={draft.image_url} alt={draft.title || 'Zdjęcie produktu'} loading="lazy" className="h-full w-full object-contain" /> : <div className="text-center text-zinc-500"><span aria-hidden="true" className="text-4xl">▧</span><p className="mt-2 text-sm">Dodaj zdjęcie produktu</p></div>}</div><div className="space-y-2 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h5 className="font-semibold text-white">{draft.title || 'Nazwa produktu'}</h5><span className="text-sm font-semibold text-amber-200">{Number.isFinite(draft.price) ? money(draft.price) : 'Ustal cenę'}</span></div>{draft.description && <p className="line-clamp-3 text-sm leading-relaxed text-zinc-400">{draft.description}</p>}<span className={`inline-block rounded-full px-2.5 py-1 text-xs ${draft.is_active ? 'bg-emerald-300/10 text-emerald-200' : 'bg-white/5 text-zinc-400'}`}>{draft.is_active ? 'Widoczny w ofercie po zapisie' : 'Ukryty w ofercie po zapisie'}</span></div></div>
        <label className="block text-sm">Nazwa produktu #{product.id}<input className={inputClass} value={draft.title} onChange={e => editDraft({ ...draft, title: e.target.value })} /></label>
        <button type="button" className={buttonClass} onClick={() => setPreviewOpen(true)}>Podgląd klienta produktu #{product.id}</button>
        {previewOpen && <GalleryProductPreviewDialog adminPreview product={{ ...draft, ...rule }} onClose={() => setPreviewOpen(false)} />}
        <label className="block text-sm">Opis produktu #{product.id}<textarea className={inputClass} value={draft.description || ''} onChange={e => editDraft({ ...draft, description: e.target.value })} /></label>
        <label className="block text-sm">Adres zdjęcia produktu #{product.id}<input className={inputClass} type="url" value={draft.image_url || ''} onChange={e => editDraft({ ...draft, image_url: e.target.value })} /></label>
        <label className="block text-sm">Dodatkowe zdjęcia produktu #{product.id} (adres w każdym wierszu)<textarea className={inputClass} rows={3} value={(draft.preview_images || []).join('\n')} onChange={e => editDraft({ ...draft, preview_images: e.target.value.split('\n') })} /></label><p className="text-xs leading-relaxed text-zinc-400">Do 12 adresów HTTPS. Kolejność wierszy określa kolejność ujęć w podglądzie; zdjęcie główne wyświetla się jako pierwsze.</p>
        <label className="block text-sm">Film produktu #{product.id} (MP4)<input className={inputClass} type="url" placeholder="https://…/film.mp4" value={draft.video_url || ''} onChange={e => editDraft({ ...draft, video_url: e.target.value })} /></label>
        <p className="text-xs text-zinc-400">Film uruchamia klient. Nie pobiera się podczas otwierania sklepu. Pusty adres usuwa film.</p>
        <label className="block text-sm">Przykładowe rozkładówki produktu #{product.id} (adres w każdym wierszu)<textarea className={inputClass} rows={3} value={(draft.sample_pages || []).join('\n')} onChange={e => editDraft({ ...draft, sample_pages: e.target.value.split('\n').map(url => url.trim()).filter(Boolean) })} /></label>
        <p className="text-xs text-zinc-400">Do 12 zdjęć rozkładówek w kolejności przeglądania. Pokazujemy je jako inspirację, nie projekt zdjęć klienta.</p>
        <div className="flex flex-wrap gap-2"><button type="button" className={buttonClass} onClick={() => setMediaOpen(true)}>Wybierz zdjęcie produktu #{product.id}</button>{draft.image_url && <button type="button" className={buttonClass} onClick={() => editDraft({ ...draft, image_url: '' })}>Usuń zdjęcie produktu #{product.id}</button>}</div>
        {!!draft.preview_images?.some(url => /^https:\/\//i.test(url)) && <div className="space-y-3"><p className="text-xs text-zinc-400">Dodatkowe ujęcia w szczegółach produktu. Zmiany zapisuje przycisk „Zapisz produkt”.</p><div className="flex flex-wrap gap-3">{draft.preview_images.map((url, index) => /^https:\/\//i.test(url) && <div key={`${url}-${index}`} className="w-28 rounded-xl border border-white/10 p-2"><img src={url} alt={`${draft.title} — ujęcie ${index + 1}`} loading="lazy" className="h-20 w-full rounded-lg bg-[#efede8] object-contain" /><button type="button" className={`${buttonClass} mt-2 w-full !px-2`} aria-label={`Usuń ujęcie ${index + 1} produktu #${product.id}`} onClick={() => editDraft({ ...draft, preview_images: draft.preview_images?.filter((_, current) => current !== index) })}>Usuń ujęcie</button></div>)}</div></div>}
        {mediaOpen && <Suspense fallback={<p role="status" className="text-sm text-zinc-400">Wczytywanie biblioteki zdjęć…</p>}><MediaPicker isOpen={mediaOpen} onClose={() => setMediaOpen(false)} onSelect={url => { editDraft({ ...draft, image_url: Array.isArray(url) ? url[0] : url }); setMediaOpen(false); }} /></Suspense>}
        <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Cena produktu #{product.id} (zł)<input className={inputClass} type="number" min={draft.is_active ? '0.01' : '0'} step="0.01" value={moneyValue(draft.price)} onChange={e => editDraft({ ...draft, price: amountFromInput(e.target.value) })} /></label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={draft.is_active} onChange={e => editDraft({ ...draft, is_active: e.target.checked })} />Produkt #{product.id} widoczny</label></div>
        {validation && <p role="alert" className="text-red-300">{validation}</p>}
        <button type="button" className={buttonClass} onClick={() => { if (!draft.title.trim() || !validAmount(draft.price) || (draft.is_active && draft.price === 0)) { setValidation('Uzupełnij nazwę. Produkt widoczny wymaga dodatniej ceny; ukryty szkic może mieć cenę 0.'); return; } if (draft.image_url && !/^https?:\/\//i.test(draft.image_url)) { setValidation('Adres zdjęcia musi zaczynać się od https:// lub http://.'); return; } const previewImages = [...new Set((draft.preview_images || []).map(url => url.trim()).filter(Boolean))]; if (previewImages.length > 12 || previewImages.some(url => !/^https:\/\//i.test(url))) { setValidation('Podaj maksymalnie 12 poprawnych adresów HTTPS zdjęć podglądu.'); return; } setValidation(''); onSave({ ...draft, preview_images: previewImages }); }}>Zapisz produkt #{product.id}</button>
        <div className="grid gap-3 border-t border-zinc-700 pt-3 sm:grid-cols-2"><label className="text-sm">Produkt #{product.id} minimum zdjęć<input className={inputClass} type="number" min="1" step="1" value={Number.isFinite(rule.minPhotos) ? rule.minPhotos : ''} onChange={e => onRule({ ...rule, minPhotos: e.target.value === '' ? NaN : Number(e.target.value) })} /></label><label className="text-sm">Produkt #{product.id} maksimum zdjęć<input className={inputClass} type="number" min="1" step="1" value={Number.isFinite(rule.maxPhotos) ? rule.maxPhotos : ''} onChange={e => onRule({ ...rule, maxPhotos: e.target.value === '' ? NaN : Number(e.target.value) })} /></label></div><p className="text-xs text-zinc-400">Limity zdjęć zapisuje przycisk „Zapisz ustawienia sklepu”.</p>
        <label className="block text-sm">Dostawa produktu #{product.id}<select className={inputClass} value={rule.deliveryMethods?.length === 1 ? rule.deliveryMethods[0] : 'all'} onChange={e => onRule({ ...rule, deliveryMethods: e.target.value === 'all' ? ['locker', 'courier'] : [e.target.value as 'locker' | 'courier'] })}><option value="all">Paczkomat lub kurier</option><option value="courier">Tylko kurier — np. duży fotoobraz</option><option value="locker">Tylko Paczkomat</option></select></label><p className="text-xs text-zinc-400">Ograniczenie dotyczy całej paczki z tym produktem. Sprawdź gabaryt opakowania i cenę przed aktywacją; zapisuje się z ustawieniami sklepu.</p>
    </fieldset>;
}
