'use client';

import {useEffect, useState} from 'react';
import GalleryShipmentPanel from '@/components/admin/GalleryShipmentPanel';
import type {ShopMetadata} from '@/lib/galleries/merchandise';

type Order = {id:number;galleryId:number;createdAt:string;total:number;paymentStatus:string;metadata:ShopMetadata;photos?:Array<{id:number;file_url:string;thumbnail_url:string|null}>};
const paymentLabels: Record<string,string> = {paid:'Opłacone',pending:'Oczekuje na płatność',cancelled:'Płatność anulowana',failed:'Płatność nieudana',failed_init:'Nie rozpoczęto płatności',refunded:'Zwrócone'};
const stageLabels: Record<string,string> = {new:'Nowe',ordered:'Zamówione u producenta',received:'Odebrane w Foto-Dron',packed:'Spakowane',shipped:'Wysłane do klienta'};
const money = (value:number) => new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN'}).format(value/100);
const button = 'inline-flex min-h-11 items-center justify-center rounded-xl border border-white/15 bg-white/[0.035] px-4 py-2.5 text-sm font-semibold text-zinc-100 transition hover:border-amber-200/40 hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-200 disabled:cursor-not-allowed disabled:opacity-40';
const input = 'mt-2 min-h-12 w-full min-w-0 rounded-xl border border-white/15 bg-zinc-950/50 px-3.5 py-3 text-base text-white focus:outline-none focus:ring-2 focus:ring-amber-200/40';
async function request(path:string, init?:RequestInit) {
 const token=localStorage.getItem('admin_token');
 const response=await fetch(`/api/${path}`,{credentials:'include',...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} : {}),...init?.headers}});
 const data=await response.json();
 if(!response.ok||data.success===false)throw Error(data.error||'Nie udało się wczytać danych. Spróbuj ponownie.');
 return data;
}
export default function MerchandiseOrderDetails({order,onUpdated}:{order:Order;onUpdated?:(metadata:ShopMetadata)=>void}) {
 const [fulfillment,setFulfillment]=useState(order.metadata.fulfillment);
 const [status,setStatus]=useState(fulfillment.status),[tracking,setTracking]=useState(fulfillment.trackingNumber||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setFulfillment(order.metadata.fulfillment);setStatus(order.metadata.fulfillment.status);setTracking(order.metadata.fulfillment.trackingNumber||'');},[order.metadata.fulfillment]);
 const pickup=order.metadata.delivery.method==='pickup';
 const labels:Record<string,string>=pickup?{new:'Nowe',ordered:'Zamówione u producenta',received:'Odebrane w Foto-Dron',packed:'Gotowe do odbioru',collected:'Odebrane przez klienta'}:stageLabels;
 const stages=Object.keys(labels);const currentStage=stages.indexOf(fulfillment.status);
 const save=async()=>{if(busy)return;setBusy(true);setError('');try{const data=await request(`admin/galleries/${order.galleryId}/shop/orders/${order.id}`,{method:'PATCH',body:JSON.stringify({status,trackingNumber:tracking})});setFulfillment(data.metadata.fulfillment);setTracking(data.metadata.fulfillment.trackingNumber||'');onUpdated?.(data.metadata);}catch(e){setError(e instanceof Error?e.message:'Nie udało się zapisać.');}finally{setBusy(false);}};
 const d=order.metadata.delivery;const paid=order.paymentStatus==='paid';
 return <details open className="group overflow-hidden rounded-2xl border border-white/10 bg-[#171719]">
  <summary className="cursor-pointer p-4 marker:text-amber-200 sm:p-5"><span className="ml-2 inline-flex max-w-[calc(100%-2rem)] flex-wrap items-center gap-x-5 gap-y-2 align-middle"><span className="font-semibold text-white">Zamówienie #{order.id}</span><span className="text-sm text-zinc-300">{d.recipientName}</span><span className="text-sm font-semibold text-amber-100">{money(order.total)}</span><span className={`rounded-full px-3 py-1 text-xs ${paid?'bg-emerald-300/10 text-emerald-200':'bg-white/5 text-zinc-400'}`}>{paymentLabels[order.paymentStatus]||order.paymentStatus}</span><span className="text-xs text-zinc-400">{labels[fulfillment.status]||fulfillment.status} · {new Date(order.createdAt).toLocaleDateString('pl-PL')}</span></span></summary>
  <div className="space-y-5 border-t border-white/10 p-4 sm:p-6">
   <div className="grid gap-5 lg:grid-cols-2"><div><h2 className="font-semibold text-white">Odbiorca i dostawa</h2><p className="mt-2 whitespace-pre-line break-words text-sm leading-relaxed text-zinc-300">{[d.recipientName,d.email,d.phone,d.method==='locker'?`Paczkomat ${d.pointCode||''}`:pickup?'Odbiór osobisty':'Kurier',pickup?d.instructions:null,!pickup?d.address?.street:null,!pickup&&d.address?`${d.address.postalCode} ${d.address.city}`:null].filter(Boolean).join('\n')}</p></div><div className="space-y-3 text-sm text-zinc-400"><p>Dostawa dla klienta: <span className="text-zinc-200">{money(d.amount)}</span></p>{fulfillment.trackingNumber&&<p className="break-all">Przesyłka: {fulfillment.trackingNumber}</p>}<p>Galeria #{order.galleryId}</p></div></div>
   <div className="space-y-3"><h3 className="font-semibold text-white">Do przygotowania</h3>{order.metadata.lines.map((line,index)=><article key={line.id||index} className="rounded-xl border border-white/10 bg-zinc-950/40 p-4"><div className="flex flex-wrap justify-between gap-2"><h4 className="font-medium text-white">{line.kind==='print'?'Odbitka':'Produkt'} · {line.title}</h4><p className="text-sm text-amber-100">{line.quantity} szt. · {money(line.lineTotal)}</p></div><div className="mt-3 flex flex-wrap gap-2">{(line.kind==='print'?[line.photoId]:line.photoIds).map(id=>{const photo=order.photos?.find(photo=>photo.id===id);return <figure key={id} className="w-20">{photo&&<img src={photo.thumbnail_url||photo.file_url} alt={`Zdjęcie #${id}`} loading="lazy" className="h-20 w-20 rounded-lg object-contain"/>}<figcaption className="text-xs text-zinc-400">#{id}{line.kind==='product'&&line.coverPhotoId===id?' · okładka':''}</figcaption></figure>;})}</div>{line.kind==='print'?<p className="mt-2 text-sm leading-relaxed text-zinc-400">Zdjęcie #{line.photoId} · {line.format?.label||line.formatId} · {line.format?.paper}{line.crop?.mode==='fit'?' · cały kadr, możliwe marginesy':' · kadr dopasowany'}</p>:<div className="mt-2 space-y-1 break-words text-sm leading-relaxed text-zinc-400"><p>{line.photoIds.length} zdjęć · okładka #{line.coverPhotoId}</p><p>Kolejność zdjęć: {line.photoIds.join(', ')}</p></div>}</article>)}</div>
   {paid?<><section aria-label="Etap realizacji" className="space-y-3"><label className="block">Etap realizacji<select className={input} value={status} onChange={e=>setStatus(e.target.value as ShopMetadata['fulfillment']['status'])}>{Object.entries(labels).filter((_,index)=>index===currentStage||index===currentStage+1).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{!pickup&&<label className="block">Numer przesyłki<input className={input} maxLength={100} value={tracking} onChange={e=>setTracking(e.target.value)}/></label>}<button type="button" className={button} disabled={busy||(status==='shipped'&&!tracking.trim())} onClick={save}>{busy?'Zapisywanie…':'Zapisz etap realizacji'}</button>{error&&<p role="alert">{error}</p>}</section><ProductionFiles galleryId={order.galleryId} orderId={order.id}/><GalleryShipmentPanel galleryId={order.galleryId} orderId={order.id} method={d.method} onShipmentChange={shipment=>{if(shipment?.state==='created'&&shipment.trackingNumber)setTracking(shipment.trackingNumber);}}/></>:<p className="rounded-xl bg-white/[0.03] p-4 text-sm text-zinc-400">Pliki do produkcji i nadanie przesyłki będą dostępne po potwierdzeniu płatności.</p>}
  </div>
 </details>;
}
function ProductionFiles({galleryId,orderId}:{galleryId:number;orderId:number}) {
 const [busy,setBusy]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState('');
 const prepare=async()=>{if(busy)return;setBusy(true);setError('');setUrl('');try{const data=await request(`admin/galleries/${galleryId}/shop/orders/${orderId}/production`,{method:'POST'});if(typeof data.url!=='string'||!/^https:\/\//i.test(data.url))throw Error('Nie otrzymano poprawnego linku do plików.');setUrl(data.url);}catch(e){setError(e instanceof Error?e.message:'Nie udało się przygotować plików.');}finally{setBusy(false);}};
 return <section aria-label={`Pliki do produkcji zamówienia ${orderId}`} className="space-y-3 rounded-2xl border border-amber-200/15 bg-amber-200/[0.04] p-4"><h3 className="font-semibold text-white">Pliki dla producenta</h3><p className="max-w-3xl text-sm leading-relaxed text-zinc-300">ZIP zawiera odbitki JPG, oryginalne zdjęcia do produktów i zestawienie zamówienia. Album lub fotoksiążka wymagają przygotowania projektu i złożenia zamówienia w nPhoto.</p><div className="flex flex-wrap gap-3"><button type="button" disabled={busy} className={button} onClick={prepare}>{busy?'Przygotowywanie plików…':'Przygotuj pliki do produkcji'}</button>{url&&<a href={url} target="_blank" rel="noopener noreferrer" className={`${button} !border-amber-200/40 !bg-amber-200/10 !text-amber-100`}>Pobierz ZIP zamówienia #{orderId}</a>}</div>{url&&<p role="status" className="text-sm text-emerald-200">Pliki są gotowe do pobrania.</p>}{error&&<p role="alert" className="text-sm text-red-200">{error}</p>}</section>;
}
