'use client';
import {useState} from 'react';
import type {ProdigiOrderState} from '@/lib/fulfillment/prodigi-orders';
export default function ProdigiOrderPanel({galleryId,orderId,initial}:{galleryId:number;orderId:number;initial?:ProdigiOrderState}){
 const [state,setState]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[approved,setApproved]=useState(false),[prepared,setPrepared]=useState(false),[providerOrderId,setProviderOrderId]=useState(''),[proofs,setProofs]=useState<Array<{lineId:string;url:string}>>([]);
 const action=async(action:string)=>{setBusy(true);setMessage('');try{const token=localStorage.getItem('admin_token');const r=await fetch(`/api/admin/galleries/${galleryId}/shop/orders/${orderId}/prodigi`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},credentials:'include',body:JSON.stringify({action,approved,providerOrderId})});const data=await r.json();if(!r.ok)throw Error(data.error||'Nie potwierdzono operacji.');if(data.fulfillment)setState(data.fulfillment);if(data.proofs)setProofs(data.proofs);if(data.prepared){setPrepared(true);setMessage(`Sprawdzono pliki. Koszt produkcji z dostawą: ${(data.prepared.input.quote.providerCostGrosze/100).toFixed(2)} PLN. ${action==='approve'?'Podgląd zatwierdzony.':'Sprawdź zdjęcia, produkt i adres przed zatwierdzeniem.'}`);}else setMessage('Stan Prodigi zapisany.');}catch(e){setMessage(e instanceof Error?e.message:'Błąd operacji.');}finally{setBusy(false);}};
 const cls='rounded-lg border border-white/20 px-4 py-3 text-sm disabled:opacity-40';
 return <section aria-label="Produkcja Prodigi" className="space-y-3 rounded-xl border border-emerald-300/20 p-4"><h3 className="font-semibold">Produkcja Prodigi</h3><p className="text-sm text-zinc-300">Przygotowanie sprawdza pliki HQ, rozdzielczość i aktualny koszt. Wysłanie zleca płatną produkcję w środowisku live. Testy sandbox są dostępne w ustawieniach sklepu.</p>{state?<><p>{state.environment} · {state.stage||state.state} · {state.orderId||state.idempotencyKey}</p>{(Boolean(state.issueCount)||state.outcome?.toLowerCase()==='createdwithissues')&&<p role="alert">Prodigi zgłasza problem z zamówieniem. Sprawdź szczegóły w panelu Prodigi przed dalszą realizacją.</p>}{state.state==='unknown'||state.state==='submitting'?<p role="alert">Wynik wymaga sprawdzenia w Prodigi. Ponowne wysłanie jest zablokowane.</p>:null}{!state.orderId&&<div className="space-y-2"><label className="block text-sm">ID znalezione w panelu Prodigi<input className="ml-2 rounded bg-zinc-900 p-2" value={providerOrderId} onChange={e=>setProviderOrderId(e.target.value)} placeholder="ord_…"/></label><button className={cls} disabled={busy||!providerOrderId} onClick={()=>action('reconcile')}>Zweryfikuj i powiąż wynik</button></div>}<div className="flex flex-wrap gap-3"><button className={cls} disabled={busy||!state.orderId} onClick={()=>action('refresh')}>Odśwież status</button><button className={cls} disabled={busy||!state.orderId||state.state==='cancelled'} onClick={()=>action('cancel')}>Poproś Prodigi o anulowanie</button></div>{state.shipments?.map(s=><p key={s.id}>{s.trackingNumber||'Brak numeru przesyłki'}{s.trackingUrl&&<a className="ml-3 underline" href={s.trackingUrl} target="_blank" rel="noopener noreferrer">Śledzenie</a>}</p>)}</>:<><button className={cls} disabled={busy} onClick={()=>action('prepare')}>Sprawdź pliki HQ i koszt</button>{proofs.map(proof=><a key={proof.lineId} href={proof.url} target="_blank" rel="noopener noreferrer" className="inline-block mr-3 text-sm underline"><img src={proof.url} alt={`Plik HQ pozycji ${proof.lineId}`} className="h-32 w-32 object-contain"/>Otwórz plik produkcyjny HQ</a>)}<label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Sprawdziłem zdjęcia, pełny kadr z możliwymi marginesami, wariant produktu i adres klienta.</label><div className="flex flex-wrap gap-3"><button className={cls} disabled={busy||!prepared||!approved} onClick={()=>action('approve')}>Zatwierdź podgląd</button><button className={cls} disabled={busy||!approved} onClick={()=>action('create')}>Zleć produkcję Prodigi</button></div></>}{message&&<p role="status" className="text-sm">{message}</p>}</section>;
}
