import type { ShopMetadata } from './merchandise';
import { orderDeliveryLabel, orderLineDetails, orderMoney, safeOrderImage } from './order-presentation';

const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Input = {id:number;total:number;metadata:ShopMetadata;url:string;admin?:boolean;photos?:Array<{id:number;url:string|null}>};
export function renderOrderEmail({id,total,metadata,url,admin=false,photos=[]}:Input) {
  const heading = admin ? `Zamówienie #${id} — do realizacji` : `Potwierdzenie zamówienia #${id}`;
  const rows = metadata.lines.map(line => {
    const productImage = line.kind==='product' ? safeOrderImage(line.product?.image_url) : null;
    const ids = line.kind==='print' ? [line.photoId] : line.photoIds;
    // Keep even a large album readable and the message below typical mail clipping limits.
    const thumbs = ids.slice(0,12).map(photoId=>{
      const image = safeOrderImage(photos.find(p=>p.id===photoId)?.url);
      return image ? `<span style="display:inline-block;width:76px;vertical-align:top;margin:4px"><img src="${escape(image)}" width="68" height="68" alt="Zdjęcie #${photoId}" style="display:block;border-radius:6px;object-fit:cover"><span style="font-size:11px;color:#666">#${photoId}${line.kind==='product' && photoId===line.coverPhotoId ? ' · okładka' : ''}</span></span>` : '';
    }).join('');
    return `<tr><td style="padding:22px 24px;border-bottom:1px solid #e8e3d9">${productImage ? `<img src="${escape(productImage)}" alt="${escape(line.title)}" width="112" style="display:block;width:112px;max-width:100%;border-radius:10px;margin-bottom:14px">` : ''}<h2 style="font-size:18px;margin:0 0 8px;color:#24211d">${escape(line.title)}</h2><p style="margin:0 0 12px;color:#625c52;font-size:13px">${escape(orderLineDetails(line))}</p><table role="presentation" width="100%" style="font-size:14px"><tr><td>Ilość</td><td>Cena za szt.</td><td align="right">Wartość</td></tr><tr><td><b>${line.quantity} szt.</b></td><td>${escape(orderMoney(line.unitAmount))}</td><td align="right"><b>${escape(orderMoney(line.lineTotal))}</b></td></tr></table>${thumbs ? `<div style="margin-top:16px">${thumbs}</div>` : ''}${ids.length>12?'<p style="font-size:12px">Pozostałe zdjęcia znajdziesz w szczegółach zamówienia.</p>':''}${admin && line.kind==='product' ? `<p style="font-size:12px;color:#625c52">Kolejność zdjęć: ${ids.join(', ')}<br>Okładka: #${line.coverPhotoId}</p>` : ''}</td></tr>`;
  }).join('');
  const button = admin ? 'Otwórz zamówienie w adminie' : 'Zobacz swoje zamówienie';
  const text = `${heading}\nPłatność potwierdzona\n\n${metadata.lines.map(l=>`${l.title}\n${orderLineDetails(l)}\n${l.quantity} szt. × ${orderMoney(l.unitAmount)} = ${orderMoney(l.lineTotal)}`).join('\n\n')}\n\n${orderDeliveryLabel(metadata)}\nDostawa: ${orderMoney(metadata.delivery.amount)}\nRazem: ${orderMoney(total)}\nOdbiorca: ${metadata.delivery.recipientName}\n${button}: ${url}`;
  const html = `<!doctype html><html lang="pl"><head><meta name="viewport" content="width=device-width, initial-scale=1"><meta charset="utf-8"></head><body style="margin:0;background:#f3f1ec;font-family:Arial,sans-serif;color:#24211d"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:24px 10px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#fff;border:1px solid #e8e3d9;border-radius:16px;overflow:hidden"><tr><td style="padding:28px 24px;background:#1c1b19;color:#f6e4b5"><p style="margin:0 0 18px;font-size:13px;letter-spacing:2px">WŁAŚNIEWSKI · FOTOGRAFIA</p><h1 style="margin:0;font-size:25px;line-height:1.3">${heading}</h1><p style="margin:14px 0 0;color:#d8edda">Płatność potwierdzona</p></td></tr>${rows}<tr><td style="padding:24px;background:#faf8f3"><h2 style="font-size:17px;margin-top:0">Odbiorca i dostawa</h2><p>${escape(metadata.delivery.recipientName)}<br>${escape(orderDeliveryLabel(metadata))}</p>${admin?`<p>${escape(metadata.delivery.email)}<br>${escape(metadata.delivery.phone)}</p>`:''}<p>Dostawa: ${escape(orderMoney(metadata.delivery.amount))}</p><p style="font-size:22px"><b>Razem: ${escape(orderMoney(total))}</b></p><a href="${escape(url)}" style="display:inline-block;background:#825e1b;color:#fff;text-decoration:none;padding:16px 20px;border-radius:8px;font-weight:bold">${button}</a><p style="font-size:12px;color:#625c52;margin-top:18px">Szczegóły zamówienia są dostępne po zalogowaniu. Miniatury są podglądami, nie plikami do druku.</p></td></tr></table></td></tr></table></body></html>`;
  return {html,text};
}
