import test from 'node:test';import assert from 'node:assert/strict';
import {orderEnvironment,orderCredentials,parseProviderOrder,prodigiOrderRequest,prodigiSnapshotSchema} from '../../src/lib/fulfillment/prodigi-orders';
test('sandbox default and explicit live credential gate',()=>{delete process.env.PRODIGI_ORDER_ENV;delete process.env.PRODIGI_LIVE_ORDERS_ENABLED;assert.equal(orderEnvironment(),'sandbox');process.env.PRODIGI_ORDER_ENV='live';assert.throws(orderEnvironment);process.env.PRODIGI_ORDER_ENV='typo';assert.throws(orderEnvironment);delete process.env.PRODIGI_ORDER_ENV;assert.throws(()=>orderCredentials('live'));});
test('provider rejects ambiguous and failure responses but supports paused ID-only creation',()=>{assert.throws(()=>parseProviderOrder({outcome:'ValidationFailed',order:{id:'ord_123'}}));assert.throws(()=>parseProviderOrder({outcome:'Created'}));assert.equal(parseProviderOrder({outcome:'OnHold',order:{id:'ord_123'}}).stage,'OnHold');assert.equal(parseProviderOrder({outcome:'AlreadyExists',order:{id:'ord_123',status:{stage:'InProgress'}}}).orderId,'ord_123');});
test('tracking excludes unsafe URLs and preserves partial cancellation stage',()=>{const value=parseProviderOrder({outcome:'FailedToCancel',order:{id:'ord_123',status:{stage:'InProgress'},shipments:[{id:'shp_1',tracking:{number:'abc',url:'javascript:alert(1)'}}]}});assert.equal(value.stage,'InProgress');assert.equal(value.shipments[0].trackingUrl,null);});
test('required asset contract and explicit variants',()=>{assert.equal(prodigiSnapshotSchema.safeParse({sku:'GLOBAL-CAN-10X10',environment:'sandbox',variant:{attributes:{}},requiredAssets:[]}).success,false);});
test('sandbox transport fixed host never retries and errors redact provider body',async()=>{process.env.PRODIGI_SANDBOX_API_KEY='fake-key';let calls=0;await assert.rejects(()=>prodigiOrderRequest('sandbox','/Orders','POST',{},async(url,init)=>{calls++;assert.equal(url,'https://api.sandbox.prodigi.com/v4.0/Orders');assert.equal(init?.redirect,'error');throw Error('secret-provider-error');}),e=>{assert.doesNotMatch(String(e),/secret-provider-error/);return true;});assert.equal(calls,1);await assert.rejects(()=>prodigiOrderRequest('sandbox','/Orders','POST',{},async()=>new Response('secret-key',{status:401})),/HTTP 401/);delete process.env.PRODIGI_SANDBOX_API_KEY;});

test('live credentials cannot be used from preview even with live enabled',()=>{process.env.PRODIGI_LIVE_ORDERS_ENABLED='true';process.env.PRODIGI_API_KEY='qa-live';process.env.GALLERY_QA_CONTEXT='deploy-preview';assert.throws(()=>orderCredentials('live'),/podglądu/);delete process.env.GALLERY_QA_CONTEXT;delete process.env.PRODIGI_LIVE_ORDERS_ENABLED;delete process.env.PRODIGI_API_KEY;});
